export const blogPosts = [
  {
    slug: "seo-strategies-2024",
    title: "SEO Strategies 2024: Dominate Search Rankings",
    description:
      "Latest SEO techniques and strategies to boost your search engine visibility and drive organic traffic.",
    category: "SEO",
    date: "2024-10-15",
    author: "MH Digital Solutions",
    image: "/images/seo-search-analytics.webp",
    featured: true,
    content:
      "Discover the latest SEO strategies for 2024 including AI-powered optimization, voice search, and core web vitals...",
  },
  {
    slug: "ai-automation-revolution-2024",
    title: "AI Automation Revolution 2024: Transform Your Business Operations",
    description:
      "Discover how AI automation is revolutionizing business processes and driving unprecedented efficiency gains.",
    category: "AI & Automation",
    date: "2024-10-10",
    author: "MH Digital Solutions",
    image: "/images/ai-analytics-data.webp",
    featured: true,
    content: "Explore how AI automation is transforming industries and driving efficiency in business operations...",
  },
  {
    slug: "mobile-app-development-trends-2024",
    title: "Mobile App Development Trends 2024",
    description: "Explore the latest mobile app development trends shaping the future of digital experiences.",
    category: "Mobile Development",
    date: "2024-10-05",
    author: "MH Digital Solutions",
    image: "/images/mobile-app-startup.webp",
    featured: true,
    content:
      "Stay ahead with the latest mobile app development trends including cross-platform development, AI integration...",
  },
  {
    slug: "digital-marketing-fundamentals",
    title: "Digital Marketing Fundamentals: Build Your Online Presence",
    description: "Master the core principles of digital marketing to establish a strong online presence.",
    category: "Digital Marketing",
    date: "2024-09-28",
    author: "MH Digital Solutions",
    image: "/images/digital-marketing-analytics.webp",
    featured: false,
    content: "Learn the fundamentals of digital marketing including SEO, PPC, social media, and content marketing...",
  },
  {
    slug: "web-design-best-practices",
    title: "Web Design Best Practices 2024",
    description: "Create stunning, user-friendly websites that convert visitors into customers.",
    category: "Web Design",
    date: "2024-09-20",
    author: "MH Digital Solutions",
    image: "/images/web-development-design.webp",
    featured: false,
    content:
      "Discover best practices for modern web design including responsive design, accessibility, and performance...",
  },
  {
    slug: "social-media-marketing-guide",
    title: "Social Media Marketing Guide: Engage Your Audience",
    description: "Strategies to build a strong social media presence and engage your target audience effectively.",
    category: "Social Media",
    date: "2024-09-15",
    author: "MH Digital Solutions",
    image: "/images/social-media-marketing-team.webp",
    featured: false,
    content:
      "Master social media marketing with strategies for content creation, engagement, and community building...",
  },
  {
    slug: "ppc-advertising-roi",
    title: "PPC Advertising: Maximize Your ROI",
    description: "Optimize your PPC campaigns to achieve maximum return on investment.",
    category: "Digital Marketing",
    date: "2024-09-10",
    author: "MH Digital Solutions",
    image: "/images/business-growth-arrow.webp",
    featured: false,
    content:
      "Learn how to create and optimize PPC campaigns for maximum ROI including keyword research, bidding strategies...",
  },
  {
    slug: "content-marketing-strategy",
    title: "Content Marketing Strategy: Drive Engagement",
    description: "Create compelling content that attracts, engages, and converts your target audience.",
    category: "Content Marketing",
    date: "2024-09-05",
    author: "MH Digital Solutions",
    image: "/images/financial-growth-investment.webp",
    featured: false,
    content:
      "Develop a comprehensive content marketing strategy including planning, creation, distribution, and measurement...",
  },
  {
    slug: "email-marketing-campaigns",
    title: "Email Marketing Campaigns: Convert Subscribers",
    description: "Build effective email marketing campaigns that drive conversions and customer loyalty.",
    category: "Digital Marketing",
    date: "2024-08-30",
    author: "MH Digital Solutions",
    image: "/images/growth-scaling-plants.webp",
    featured: false,
    content:
      "Master email marketing with strategies for list building, segmentation, personalization, and automation...",
  },
  {
    slug: "business-analytics-insights",
    title: "Business Analytics: Data-Driven Decisions",
    description: "Leverage analytics to make informed business decisions and measure marketing success.",
    category: "Business Consulting",
    date: "2024-08-25",
    author: "MH Digital Solutions",
    image: "/images/app-development-ui.webp",
    featured: false,
    content: "Learn how to use business analytics to track performance, identify trends, and optimize strategies...",
  },
  {
    slug: "ecommerce-optimization",
    title: "E-Commerce Optimization: Boost Sales",
    description: "Strategies to optimize your e-commerce store and increase online sales.",
    category: "E-Commerce",
    date: "2024-08-20",
    author: "MH Digital Solutions",
    image: "/images/digital-marketing-analytics.webp",
    featured: false,
    content:
      "Discover e-commerce optimization techniques including product pages, checkout optimization, and conversion rate...",
  },
  {
    slug: "local-seo-guide",
    title: "Local SEO Guide: Dominate Local Search",
    description: "Master local SEO to attract customers in your geographic area.",
    category: "SEO",
    date: "2024-08-15",
    author: "MH Digital Solutions",
    image: "/images/seo-search-analytics.webp",
    featured: false,
    content: "Learn local SEO strategies including Google My Business optimization, local citations, and reviews...",
  },
]

export const categories = [
  "SEO",
  "Digital Marketing",
  "Web Design",
  "Web Development",
  "Mobile Development",
  "AI & Automation",
  "Business Consulting",
  "E-Commerce",
  "Content Marketing",
  "Social Media",
]

export const caseStudies = [
  {
    slug: "techcorp-ai-automation",
    title: "TechCorp AI Automation: $2M Annual Savings",
    description: "How we helped TechCorp achieve massive cost savings through intelligent AI automation solutions.",
    industry: "Technology",
    image: "/images/ai-analytics-data.webp",
    metrics: {
      savings: "$2M",
      timeReduction: "60%",
      efficiency: "300%",
    },
    challenge: "TechCorp was struggling with manual processes that consumed significant resources and time.",
    solution: "We implemented AI-powered automation across their operations, reducing manual work by 60%.",
    result: "Achieved $2M in annual savings and 300% efficiency improvement.",
    featured: true,
  },
  {
    slug: "fitlife-gyms-scaling",
    title: "FitLife Gyms: 300% Growth Through Digital Marketing",
    description: "Discover how our comprehensive digital strategy helped FitLife Gyms scale across multiple locations.",
    industry: "Fitness",
    image: "/images/growth-scaling-plants.webp",
    metrics: {
      growth: "300%",
      members: "5000+",
      locations: "15",
    },
    challenge: "FitLife Gyms wanted to expand but lacked a cohesive digital marketing strategy.",
    solution: "We developed a comprehensive digital marketing strategy including SEO, PPC, and social media.",
    result: "Achieved 300% growth and expanded to 15 locations with 5000+ members.",
    featured: true,
  },
  {
    slug: "healthcare-digital-transformation",
    title: "Healthcare Digital Transformation Success",
    description:
      "Complete digital transformation of a healthcare provider improving patient experience and operational efficiency.",
    industry: "Healthcare",
    image: "/images/app-development-ui.webp",
    metrics: {
      patientSatisfaction: "95%",
      efficiency: "40%",
      appointments: "200%",
    },
    challenge: "Healthcare provider needed to modernize their digital presence and patient experience.",
    solution: "We implemented a complete digital transformation including website redesign and patient portal.",
    result: "Improved patient satisfaction to 95% and increased appointments by 200%.",
    featured: true,
  },
  {
    slug: "restaurant-digital-transformation",
    title: "Restaurant Digital Transformation: 250% Online Orders",
    description:
      "How we transformed a traditional restaurant into a digital-first business with online ordering and delivery integration.",
    industry: "Food & Beverage",
    image: "/images/digital-marketing-analytics.webp",
    metrics: {
      onlineOrders: "250%",
      revenue: "180%",
      customers: "3000+",
    },
    challenge: "Traditional restaurant struggling with limited online presence and no digital ordering system.",
    solution:
      "Implemented complete digital transformation: website redesign, online ordering system, delivery integration, and social media marketing.",
    result: "Achieved 250% increase in online orders, 180% revenue growth, and 3000+ new customers.",
    featured: true,
  },
  {
    slug: "drilling-supply-gillette-wy",
    title: "Drilling Supply Company (Gillette, WY): 125% Lead Increase",
    description:
      "B2B drilling supply company in Gillette, Wyoming achieved massive lead generation through targeted digital marketing.",
    industry: "Industrial Supply",
    image: "/images/business-growth-arrow.webp",
    metrics: {
      leads: "125%",
      contracts: "85%",
      revenue: "150%",
    },
    challenge: "Drilling supply company in Gillette needed to generate qualified B2B leads in competitive market.",
    solution: "Implemented targeted SEO, PPC, and content marketing focused on drilling industry keywords.",
    result: "125% increase in qualified leads, 85% conversion to contracts, 150% revenue growth.",
    featured: false,
  },
  {
    slug: "law-firm-morgantown-wv",
    title: "Law Firm (Morgantown, WV): 42% Consultation Increase",
    description:
      "Professional law firm in Morgantown, West Virginia increased consultations through local SEO and reputation management.",
    industry: "Legal Services",
    image: "/images/seo-search-analytics.webp",
    metrics: {
      consultations: "42%",
      rankings: "5 #1",
      reviews: "4.9",
    },
    challenge: "Law firm in Morgantown competing with larger firms for local clients.",
    solution: "Implemented local SEO strategy, Google My Business optimization, and review management.",
    result: "42% increase in consultations, 5 page-1 rankings, 4.9-star rating with 127 reviews.",
    featured: false,
  },
  {
    slug: "auto-repair-olathe-ks",
    title: "Auto Repair (Olathe, KS): 240% Traffic Increase",
    description: "Local auto repair shop in Olathe, Kansas achieved top rankings and massive traffic growth.",
    industry: "Automotive Services",
    image: "/images/web-development-design.webp",
    metrics: {
      traffic: "240%",
      ranking: "Top 3",
      customers: "500+",
    },
    challenge: "Auto repair shop in Olathe needed to compete with national chains for local customers.",
    solution: "Implemented comprehensive local SEO, website optimization, and local citation building.",
    result: "240% traffic increase, top 3 ranking for key terms, 500+ new customers.",
    featured: false,
  },
  {
    slug: "jackson-hole-resort-wy",
    title: "Jackson Hole Resort (WY): 300% Booking Increase",
    description:
      "Luxury resort in Jackson Hole, Wyoming increased bookings through digital marketing and website optimization.",
    industry: "Hospitality",
    image: "/images/financial-growth-investment.webp",
    metrics: {
      bookings: "300%",
      revenue: "280%",
      occupancy: "92%",
    },
    challenge: "Resort in Jackson Hole needed to increase bookings during peak and off-season.",
    solution: "Implemented website redesign, PPC campaigns, and seasonal marketing strategy.",
    result: "300% booking increase, 280% revenue growth, 92% occupancy rate.",
    featured: false,
  },
  {
    slug: "manufacturing-automation",
    title: "Manufacturing Automation: 45% Cost Reduction",
    description: "Manufacturing company implemented AI automation reducing operational costs significantly.",
    industry: "Manufacturing",
    image: "/images/ai-analytics-data.webp",
    metrics: {
      costReduction: "45%",
      productivity: "65%",
      downtime: "-80%",
    },
    challenge: "Manufacturing facility had high operational costs and inefficient processes.",
    solution: "Implemented AI-powered automation and process optimization.",
    result: "45% cost reduction, 65% productivity increase, 80% reduction in downtime.",
    featured: false,
  },
  {
    slug: "ecommerce-laramie-wy",
    title: "E-Commerce Store (Laramie, WY): $180K First Month",
    description: "New e-commerce store in Laramie, Wyoming launched and achieved $180K in first month sales.",
    industry: "E-Commerce",
    image: "/images/app-development-ui.webp",
    metrics: {
      firstMonth: "$180K",
      customers: "1200+",
      conversion: "3.8%",
    },
    challenge: "New e-commerce startup needed rapid growth and market penetration.",
    solution: "Implemented complete e-commerce solution with PPC, SEO, and email marketing.",
    result: "$180K first month sales, 1200+ customers, 3.8% conversion rate.",
    featured: false,
  },
  {
    slug: "ppc-campaign-casper-wy",
    title: "PPC Campaign (Casper, WY): Doubled Qualified Leads",
    description: "Service company in Casper, Wyoming doubled qualified leads through optimized PPC campaigns.",
    industry: "Services",
    image: "/images/business-growth-arrow.webp",
    metrics: {
      leads: "100%",
      costPerLead: "-35%",
      roi: "450%",
    },
    challenge: "Service company in Casper needed more qualified leads at lower cost.",
    solution: "Implemented advanced PPC optimization and audience targeting.",
    result: "Doubled qualified leads, 35% reduction in cost per lead, 450% ROI.",
    featured: false,
  },
  {
    slug: "premium-auto-detailing-expansion",
    title: "Premium Auto Detailing: Multi-Location Expansion",
    description: "Auto detailing company expanded from 1 to 5 locations through digital marketing.",
    industry: "Automotive Services",
    image: "/images/social-media-marketing-team.webp",
    metrics: {
      locations: "5",
      revenue: "400%",
      customers: "2000+",
    },
    challenge: "Auto detailing business wanted to expand to multiple locations.",
    solution: "Implemented location-based marketing and franchise support strategy.",
    result: "Expanded to 5 locations, 400% revenue growth, 2000+ customers.",
    featured: false,
  },
  {
    slug: "mobile-app-success-story",
    title: "Mobile App Success: 50K Downloads in 3 Months",
    description: "Mobile app achieved 50K downloads in 3 months through strategic app marketing.",
    industry: "Technology",
    image: "/images/mobile-app-startup.webp",
    metrics: {
      downloads: "50K",
      rating: "4.8",
      users: "35K",
    },
    challenge: "New mobile app needed rapid user acquisition and positive reviews.",
    solution: "Implemented app store optimization, social media marketing, and influencer partnerships.",
    result: "50K downloads in 3 months, 4.8-star rating, 35K active users.",
    featured: false,
  },
]

export const industries = [
  "Technology",
  "Fitness",
  "Healthcare",
  "Food & Beverage",
  "Industrial Supply",
  "Legal Services",
  "Automotive Services",
  "Hospitality",
  "Manufacturing",
  "E-Commerce",
  "Services",
  "All",
]
