export const blogPosts = [
  {
    slug: "dual-track-seo-strategy",
    title: "The Dual-Track SEO Strategy: How to Rank in a Global (US) and Niche (Malta) Market Simultaneously",
    date: "January 10, 2025",
    author: "Mohammad Hassan",
    category: "SEO",
    image: "/images/blog-dual-track-seo.webp",
    description:
      "Master the art of ranking in both broad US markets and hyper-local Malta searches with our proven dual-track SEO framework. Includes keyword mapping, hreflang setup, and content strategies.",
    featured: true,
  },
  {
    slug: "digital-marketing-services-valletta-malta",
    title: "Digital Marketing Services in Valletta Malta: Complete Guide for Local Businesses",
    date: "January 9, 2025",
    author: "Sarah Johnson",
    category: "Digital Marketing",
    image: "/images/blog-valletta-marketing.webp",
    description:
      "Unlock your business's growth potential with expert digital marketing services in Valletta Malta. Tailored strategies for social media, PPC, and reputation management.",
    featured: true,
  },
  {
    slug: "affordable-seo-agency-billings-montana",
    title: "Affordable SEO Agency in Billings Montana: Boost Your Local Rankings",
    date: "January 8, 2025",
    author: "Mike Chen",
    category: "SEO",
    image: "/images/blog-billings-seo.webp",
    description:
      "Searching for an affordable SEO agency in Billings Montana? Our local SEO experts specialize in Montana business growth with proven strategies.",
    featured: false,
  },
  {
    slug: "best-web-design-company-wichita-kansas",
    title: "Best Web Design Company in Wichita Kansas: Responsive & Conversion-Focused",
    date: "January 7, 2025",
    author: "Sarah Johnson",
    category: "Web Development",
    image: "/images/blog-wichita-web-design.webp",
    description:
      "Partner with the best web design company in Wichita Kansas for stunning, responsive websites that convert visitors into loyal customers.",
    featured: false,
  },
  {
    slug: "small-business-consulting-charleston-wv",
    title: "Small Business Consulting Firms in Charleston WV: Strategic Growth Partners",
    date: "January 6, 2025",
    author: "Mohammad Hassan",
    category: "Business Consulting",
    image: "/images/blog-charleston-consulting.webp",
    description:
      "Expert small business consulting in Charleston WV. Strategic planning, market analysis, and technology integration tailored for local companies.",
    featured: false,
  },
  {
    slug: "ecommerce-solutions-casper-wyoming",
    title: "Ecommerce Solutions for Small Business in Casper WY: Shopify & WooCommerce Experts",
    date: "January 5, 2025",
    author: "Mike Chen",
    category: "E-commerce",
    image: "/images/blog-casper-ecommerce.webp",
    description:
      "Maximize your online sales with tailored ecommerce solutions for small businesses in Casper WY. Shopify and WooCommerce development specialists.",
    featured: false,
  },
  {
    slug: "shopify-experts-anchorage-alaska",
    title: "Reliable Shopify Experts in Anchorage Alaska: Store Setup & Marketing",
    date: "January 4, 2025",
    author: "Sarah Johnson",
    category: "E-commerce",
    image: "/images/blog-anchorage-shopify.webp",
    description:
      "Experienced Shopify experts in Anchorage Alaska help businesses build and customize stores that convert. From design to marketing strategy.",
    featured: false,
  },
  {
    slug: "ai-automation-tools-montana-businesses",
    title: "AI Automation Tools for Local Businesses Montana: Streamline Operations & Cut Costs",
    date: "January 3, 2025",
    author: "Mohammad Hassan",
    category: "AI & Automation",
    image: "/images/blog-montana-ai-automation.webp",
    description:
      "Leverage AI automation tools to streamline operations and cut costs for local businesses in Montana. Enhance efficiency with cutting-edge AI.",
    featured: false,
  },
  {
    slug: "workflow-automation-malta-city",
    title: "Affordable Workflow Automation in Malta City: Increase Productivity & Reduce Errors",
    date: "January 2, 2025",
    author: "Mike Chen",
    category: "AI & Automation",
    image: "/images/blog-malta-workflow-automation.webp",
    description:
      "Increase productivity and reduce errors with affordable workflow automation solutions customized for businesses in Malta City.",
    featured: false,
  },
  {
    slug: "digital-marketing-agency-glendive-montana",
    title: "Best Digital Marketing Agency near Glendive Montana: Local SEO & PPC Experts",
    date: "January 1, 2025",
    author: "Sarah Johnson",
    category: "Digital Marketing",
    image: "/images/blog-glendive-marketing.webp",
    description:
      "Choose the best digital marketing agency near Glendive Montana for expert local SEO, PPC, and content marketing with data-driven strategies.",
    featured: false,
  },
  {
    slug: "seo-for-restaurants-malta",
    title: "How to Improve SEO for Restaurants in Malta: Google My Business & Local Citations",
    date: "December 31, 2024",
    author: "Mohammad Hassan",
    category: "SEO",
    image: "/images/blog-malta-restaurant-seo.webp",
    description:
      "Improve your restaurant's online visibility in Malta with targeted SEO strategies including Google My Business optimization and review management.",
    featured: false,
  },
  {
    slug: "ai-automation-revolution-2024",
    title: "How AI Automation is Revolutionizing Small Business Operations in 2024",
    date: "December 15, 2024",
    author: "Mohammad Hassan",
    category: "AI & Automation",
    image: "/images/3d-business-collaboration.webp",
    description:
      "Discover how AI automation is helping small businesses reduce costs by 70% while improving efficiency and customer satisfaction. Real case studies and implementation strategies included.",
    featured: true,
  },
  {
    slug: "mobile-app-development-trends-2024",
    title: "Mobile App Development Trends That Will Dominate 2024",
    date: "December 18, 2024",
    author: "Sarah Johnson",
    category: "Mobile Development",
    image: "/images/3d-shopping-online-app.webp",
    description:
      "Explore the latest mobile app development trends including AI integration, cross-platform solutions, and user experience innovations that are shaping the industry.",
    featured: true,
  },
  {
    slug: "ecommerce-optimization-strategies",
    title: "E-commerce Optimization: Converting Visitors into Loyal Customers",
    date: "December 12, 2024",
    author: "Mike Chen",
    category: "E-commerce",
    image: "/images/3d-web-design-pages.webp",
    description:
      "Learn advanced e-commerce optimization techniques that increase conversion rates, improve user experience, and build customer loyalty for sustainable growth.",
    featured: true,
  },
  {
    slug: "seo-strategies-2024",
    title: "10 SEO Strategies That Will Dominate Search Rankings in 2024",
    date: "December 10, 2024",
    author: "Sarah Johnson",
    category: "SEO",
    image: "/images/website-setup-concept.webp",
    description:
      "Discover the latest SEO techniques that are driving organic traffic growth for businesses worldwide. From technical SEO to content optimization.",
    featured: true,
  },
  {
    slug: "social-media-roi-measurement",
    title: "Measuring Social Media ROI: Advanced Analytics for Business Growth",
    date: "December 8, 2024",
    author: "Mike Chen",
    category: "Social Media",
    image: "/images/website-social-network.webp",
    description:
      "Learn how to track and measure the real impact of your social media marketing efforts with advanced analytics and attribution models.",
    featured: true,
  },
]

export const caseStudies = [
  {
    slug: "premium-auto-detailing-expansion",
    title: "Premium Auto Detailing: Boosting Local Leads with Affordable SEO",
    industry: "Automotive Services",
    image: "/images/system-update-flat.webp",
    description:
      "Local detailing business with excellent service but limited to neighborhood customers, struggling with lead generation and online visibility.",
    results: "+1200% Leads, +800% Revenue",
    metrics: { expansion: "50 States", leads: "+1200%", revenue: "+800%" },
    featured: true,
  },
  {
    slug: "mobile-app-success-story",
    title: "Mobile App Development: From Concept to 1M+ Downloads",
    industry: "Technology",
    image: "/images/api-integration-developer.webp",
    description:
      "Startup with innovative app idea but no technical expertise, needed end-to-end mobile app development and launch strategy.",
    results: "1M+ Downloads, $2M Revenue",
    metrics: { downloads: "1M+", revenue: "$2M", rating: "4.8★" },
    featured: true,
  },
  {
    slug: "saas-growth-strategy",
    title: "SaaS Company Achieves 300% Growth with Integrated Digital Strategy",
    industry: "Software as a Service (SaaS)",
    image: "/images/case-study-saas-growth.webp",
    description:
      "Low customer acquisition cost and limited brand visibility in a competitive market. Implemented comprehensive digital marketing strategy including advanced SEO, targeted PPC campaigns, and content marketing.",
    results: "300% Leads, 50% CAC Reduction",
    metrics: { leads: "+300%", cac: "-50%", keywords: "15+ Top 3" },
    featured: false,
  },
  {
    slug: "rebranding-digital-success",
    title: "Global Retailer's Rebranding Leads to 40% Online Sales Boost",
    industry: "Retail & E-commerce",
    image: "/images/case-study-rebranding.webp",
    description:
      "Outdated brand image and declining online engagement post-rebranding. Executed full digital rebranding across all platforms with website redesign and social media strategy overhaul.",
    results: "40% Sales Increase, 25% Engagement Growth",
    metrics: { sales: "+40%", engagement: "+25%", conversion: "+15%" },
    featured: false,
  },
  {
    slug: "mobile-banking-app-launch",
    title: "FinTech Startup Launches Secure Mobile Banking App, Gains 100K Users",
    industry: "FinTech",
    image: "/images/case-study-mobile-banking.webp",
    description:
      "Developing a secure, scalable, and user-friendly mobile banking application from scratch with robust security features and intuitive UI/UX.",
    results: "100K+ Users, 4.8★ Rating",
    metrics: { users: "100K+", rating: "4.8★", security: "Zero Incidents" },
    featured: false,
  },
  {
    slug: "cloud-optimization-cost-savings",
    title: "Enterprise Achieves 30% Cost Savings with Cloud Optimization",
    industry: "Enterprise Solutions",
    image: "/images/case-study-cloud-optimization.webp",
    description:
      "Spiraling cloud costs and inefficient resource utilization across multiple cloud environments. Conducted thorough cloud audit and implemented cost optimization strategies.",
    results: "30% Cost Reduction, 20% Performance Gain",
    metrics: { costs: "-30%", performance: "+20%", efficiency: "+40%" },
    featured: false,
  },
]

export const pricingPlans = [
  {
    name: "Starter Boost",
    tagline: "Perfect Launch Pad for New Businesses",
    originalPrice: "$299",
    price: "$149",
    frequency: "per week",
    discount: "50% OFF",
    features: [
      "5-page SEO-optimized website (mobile-friendly)",
      "Free hosting for life with annual contract",
      "2-month complimentary basic SEO",
      "Google Business Profile Setup & Optimization",
      "8 social media posts/month (2 platforms)",
      "Social media content creation (images, flyers, videos)",
      "Local business networking & collaboration setup",
      "Bi-weekly analytics reports & lead gen strategy",
      "FREE: $500 Google Ads credit",
      "FREE: Logo design & brand kit",
    ],
    buttonText: "Start Your Journey",
    highlight: false,
    promoBadge: { text: "New Business Special", color: "bg-green-500" },
    targetAudience: {
      title: "Perfect For:",
      description: "New businesses, startups, and local ventures launching their first professional online presence.",
      why: "Get everything you need to establish credibility and start attracting customers from day one.",
    },
    successMetrics: {
      avgIncrease: "200% increase in online visibility",
      timeToResults: "Results within 21 days",
      clientSatisfaction: "96% client satisfaction rate",
    },
    testimonial: {
      text: "Within 3 weeks of launching, we had our first 25 online customers. The ROI has been incredible!",
      author: "Maria S., Boutique Owner",
    },
  },
  {
    name: "Growth Accelerator",
    tagline: "Transform & Scale Your Digital Presence",
    originalPrice: "$499",
    price: "$249",
    frequency: "per week",
    discount: "50% OFF",
    features: [
      "Complete website redesign (UX/UI overhaul)",
      "Advanced SEO migration & technical optimization",
      "Comprehensive backlink building strategy",
      "Monthly rank tracking (15 keywords)",
      "Automated review & reputation management",
      "Social media management (3 platforms)",
      "Local SEO & citation building (25 directories)",
      "Monthly 'Growth Strategy' consultation call",
      "FREE: Conversion rate optimization audit",
      "FREE: Competitor analysis report",
    ],
    buttonText: "Accelerate Growth",
    highlight: true,
    promoBadge: { text: "Most Popular", color: "bg-fuchsia-500" },
    targetAudience: {
      title: "Perfect For:",
      description: "Established businesses with outdated websites that need a complete digital transformation.",
      why: "Revitalize your online presence and convert more visitors into paying customers.",
    },
    successMetrics: {
      avgIncrease: "350% increase in qualified leads",
      timeToResults: "Results within 45 days",
      clientSatisfaction: "98% client satisfaction rate",
    },
    testimonial: {
      text: "Our website conversion rate went from 1.2% to 4.8% after the redesign. We're booking 3x more appointments!",
      author: "James T., Dental Practice Owner",
    },
  },
]

export const categories = [
  "All",
  "AI & Automation",
  "SEO",
  "Social Media",
  "PPC",
  "Web Development",
  "Email Marketing",
  "Business Analytics",
  "HR Technology",
  "Productivity",
  "Mobile Development",
  "E-commerce",
  "Digital Marketing",
  "Business Consulting",
]

export const industries = [
  "All",
  "Automotive Services",
  "Food & Beverage",
  "Technology",
  "Fitness & Wellness",
  "SaaS",
  "Healthcare",
  "Manufacturing",
  "Retail & E-commerce",
  "FinTech",
  "Enterprise Solutions",
]
