// Blog Posts Data
export const blogPosts = [
  {
    slug: "seo-strategy-2024",
    title: "Complete SEO Strategy Guide for 2024: Dominate Local Search Rankings",
    description:
      "Learn the proven SEO strategies that help businesses rank #1 in local search results and attract qualified leads.",
    category: "SEO",
    date: "December 15, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
    content: `
      <h2>Introduction</h2>
      <p>SEO has evolved significantly in 2024. This guide covers the latest strategies that actually work.</p>
      <h2>Key Strategies</h2>
      <ul>
        <li>Technical SEO fundamentals</li>
        <li>Content optimization for E-E-A-T</li>
        <li>Local SEO for multi-location businesses</li>
        <li>Link building strategies</li>
      </ul>
    `,
  },
  {
    slug: "digital-marketing-trends",
    title: "Top 10 Digital Marketing Trends Dominating 2024",
    description: "Discover the digital marketing trends that are reshaping how businesses connect with customers.",
    category: "Digital Marketing",
    date: "December 10, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
    content: `<h2>2024 Marketing Trends</h2><p>AI, personalization, and video content are leading the way...</p>`,
  },
  {
    slug: "web-design-best-practices",
    title: "Web Design Best Practices: Creating High-Converting Websites",
    description: "Master the principles of web design that convert visitors into customers.",
    category: "Web Design",
    date: "December 5, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
    content: `<h2>Design Principles</h2><p>User experience, mobile optimization, and conversion optimization...</p>`,
  },
  {
    slug: "ppc-advertising-guide",
    title: "PPC Advertising Mastery: Generate Qualified Leads with Google Ads",
    description: "Complete guide to running profitable PPC campaigns that deliver ROI.",
    category: "PPC Advertising",
    date: "November 28, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>PPC Strategy</h2><p>Keyword research, ad copy, landing pages, and optimization...</p>`,
  },
  {
    slug: "social-media-marketing",
    title: "Social Media Marketing Strategy: Build Your Brand Community",
    description: "Proven strategies for growing your social media presence and engaging your audience.",
    category: "Social Media",
    date: "November 20, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>Social Strategy</h2><p>Content calendar, engagement tactics, and community building...</p>`,
  },
  {
    slug: "ecommerce-optimization",
    title: "E-Commerce Optimization: Increase Sales and Reduce Cart Abandonment",
    description: "Strategies to optimize your online store and maximize revenue.",
    category: "E-Commerce",
    date: "November 15, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>E-Commerce Tips</h2><p>Product pages, checkout optimization, and conversion rate optimization...</p>`,
  },
  {
    slug: "ai-automation-business",
    title: "AI Automation for Business: Streamline Operations and Boost Productivity",
    description: "How to leverage AI and automation to transform your business operations.",
    category: "AI & Automation",
    date: "November 10, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>AI Applications</h2><p>Chatbots, workflow automation, and predictive analytics...</p>`,
  },
  {
    slug: "content-marketing-strategy",
    title: "Content Marketing Strategy: Attract and Engage Your Target Audience",
    description: "Build a content marketing strategy that drives traffic and establishes authority.",
    category: "Content Marketing",
    date: "November 5, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>Content Strategy</h2><p>Blog posts, videos, infographics, and distribution channels...</p>`,
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development: From Concept to Launch",
    description: "Complete guide to developing and launching a successful mobile application.",
    category: "Mobile Development",
    date: "October 30, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>App Development</h2><p>Planning, design, development, testing, and launch...</p>`,
  },
  {
    slug: "business-consulting-tips",
    title: "Business Consulting: Strategic Growth Planning for Your Company",
    description: "Expert consulting strategies to accelerate your business growth.",
    category: "Business Consulting",
    date: "October 25, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>Consulting Services</h2><p>Strategy, operations, and growth planning...</p>`,
  },
  {
    slug: "local-seo-montana",
    title: "Local SEO for Montana Businesses: Dominate Your Local Market",
    description: "Proven local SEO strategies for Montana businesses to rank higher and attract local customers.",
    category: "SEO",
    date: "October 20, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>Montana Local SEO</h2><p>Google Business Profile, local citations, and location-specific content...</p>`,
  },
  {
    slug: "conversion-rate-optimization",
    title: "Conversion Rate Optimization: Turn Visitors into Customers",
    description: "Techniques to optimize your website and increase conversion rates.",
    category: "Digital Marketing",
    date: "October 15, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>CRO Strategies</h2><p>A/B testing, user experience, and persuasion principles...</p>`,
  },
  {
    slug: "email-marketing-campaigns",
    title: "Email Marketing Campaigns: Build Relationships and Drive Sales",
    description: "Master email marketing to nurture leads and increase customer lifetime value.",
    category: "Content Marketing",
    date: "October 10, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>Email Strategy</h2><p>Segmentation, personalization, and automation...</p>`,
  },
  {
    slug: "video-marketing-strategy",
    title: "Video Marketing Strategy: Engage Your Audience with Compelling Video Content",
    description: "How to create and distribute video content that drives engagement and conversions.",
    category: "Content Marketing",
    date: "October 5, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>Video Content</h2><p>YouTube optimization, video ads, and live streaming...</p>`,
  },
  {
    slug: "brand-building-guide",
    title: "Brand Building Guide: Create a Memorable Brand Identity",
    description: "Strategies to build a strong brand that resonates with your target audience.",
    category: "Business Consulting",
    date: "September 30, 2024",
    author: "MH Digital Solution",
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
    content: `<h2>Brand Strategy</h2><p>Logo design, brand voice, and brand positioning...</p>`,
  },
]

// Blog Categories
export const categories = [
  "All",
  "SEO",
  "Digital Marketing",
  "Web Design",
  "PPC Advertising",
  "Social Media",
  "E-Commerce",
  "AI & Automation",
  "Content Marketing",
  "Mobile Development",
  "Business Consulting",
]

// Case Studies Data
export const caseStudies = [
  {
    slug: "drilling-supply-gillette-wy",
    title: "How We Increased Leads by 125% for a Drilling Supply Company in Gillette, WY",
    description:
      "B2B digital marketing strategy that transformed lead generation for a drilling supply distributor targeting high-value contracts.",
    category: "B2B Marketing",
    industry: "Industrial Supply",
    location: "Gillette, Wyoming",
    client: "Rocky Mountain Drilling Supply",
    challenge:
      "Low visibility in B2B search results, competing against national suppliers with larger marketing budgets.",
    solution:
      "Implemented technical SEO, created industry-specific content targeting 'drilling supply leads Gillette' and 'B2B industrial marketing Wyoming', optimized for high-intent keywords.",
    results: [
      "125% increase in qualified leads",
      "3 new enterprise contracts worth $500K+",
      "Ranked #1 for 'drilling supply Gillette WY'",
      "45% improvement in lead quality score",
    ],
    metrics: { leadIncrease: "125%", contractValue: "$500K+", timeframe: "6 months", roi: "340%" },
    featured: true,
    image: "/placeholder.svg?height=400&width=600",
    content: `<h2>The Challenge</h2><p>Rocky Mountain Drilling Supply was losing market share to national competitors...</p>`,
  },
  {
    slug: "morgantown-law-firm-seo",
    title: "Morgantown Law Firm Achieves 1st Page Ranking for 5 Key Practice Areas & 42% Increase in Consultations",
    description:
      "Professional services SEO strategy that dominated local search for a specialized law firm targeting high-value cases.",
    category: "Professional Services",
    industry: "Legal Services",
    location: "Morgantown, West Virginia",
    client: "Mountain State Legal Group",
    challenge:
      "Invisible for key transactional keywords like 'Morgantown DUI lawyer' and 'family law attorney Morgantown'.",
    solution: "Comprehensive local SEO strategy with practice area-specific landing pages and authority building.",
    results: [
      "42% increase in consultation calls",
      "5 practice areas on Google Page 1",
      "28% growth in organic traffic",
      "#1 ranking for 'Morgantown DUI lawyer'",
    ],
    metrics: { consultationIncrease: "42%", pageOneRankings: 5, trafficGrowth: "28%", timeframe: "6 months" },
    featured: true,
    image: "/placeholder.svg?height=400&width=600",
    content: `<h2>The Challenge</h2><p>Mountain State Legal Group was a well-established firm but invisible online...</p>`,
  },
  {
    slug: "automotive-repair-olathe-ks",
    title: "From Page 3 to Top 3: Boosting Local Foot Traffic for an Automotive Repair Shop in Olathe, KS",
    description:
      "Local SEO transformation that increased foot traffic and service bookings for a family-owned auto repair business.",
    category: "Local Services",
    industry: "Automotive Services",
    location: "Olathe, Kansas",
    client: "Premier Auto Repair Olathe",
    challenge:
      "Buried on page 3 for 'auto repair Olathe', losing customers to competitors with better online visibility.",
    solution: "Complete local SEO overhaul including Google Business Profile optimization and review generation.",
    results: [
      "240% increase in organic traffic",
      "Top 3 ranking for 'auto repair Olathe'",
      "35% increase in service bookings",
      "150+ new 5-star reviews",
    ],
    metrics: { trafficIncrease: "240%", bookingIncrease: "35%", reviewsGenerated: 150, ranking: "Top 3" },
    featured: true,
    image: "/placeholder.svg?height=400&width=600",
    content: `<h2>The Challenge</h2><p>Premier Auto Repair was losing customers to competitors with better online presence...</p>`,
  },
  {
    slug: "jackson-hole-resort-redesign",
    title: "300% Increase in Direct Bookings for a Jackson Hole Resort Website Redesign",
    description:
      "Hospitality web design and conversion optimization that transformed a resort's online booking performance.",
    category: "Web Design & Development",
    industry: "Hospitality & Tourism",
    location: "Jackson Hole, Wyoming",
    client: "Mountain Peak Resort Jackson Hole",
    challenge: "Outdated website with poor user experience and low conversion rate (0.8%).",
    solution: "Complete website redesign with modern UX and integrated booking system.",
    results: [
      "300% increase in direct bookings",
      "Conversion rate improved from 0.8% to 3.2%",
      "Average booking value increased 45%",
      "$2.1M additional annual revenue",
    ],
    metrics: { bookingIncrease: "300%", conversionRate: "3.2%", revenueIncrease: "$2.1M", timeframe: "4 months" },
    featured: true,
    image: "/placeholder.svg?height=400&width=600",
    content: `<h2>The Challenge</h2><p>Mountain Peak Resort had a dated website that didn't reflect the quality of their property...</p>`,
  },
  {
    slug: "affordable-seo-package-wichita",
    title: "Saves $5k Annually by Switching to Our Affordable SEO Package (Wichita, KS)",
    description: "Cost-effective SEO solution that delivered enterprise-level results at a fraction of the price.",
    category: "SEO Services",
    industry: "Digital Marketing",
    location: "Wichita, Kansas",
    client: "Midwest Manufacturing Co.",
    challenge: "Paying $3,500/month to a national agency with minimal results.",
    solution: "Customized affordable SEO package with transparent pricing and dedicated account management.",
    results: [
      "Saved $5,000 annually",
      "Better results than previous agency",
      "Transparent monthly reporting",
      "ROI increased 180%",
    ],
    metrics: { monthlySavings: "$417", annualSavings: "$5,000", roiIncrease: "180%", timeframe: "12 months" },
    featured: false,
    image: "/placeholder.svg?height=400&width=600",
    content: `<h2>The Challenge</h2><p>Midwest Manufacturing was paying $3,500/month but wasn't seeing results...</p>`,
  },
  {
    slug: "technical-seo-audit-cheyenne",
    title: "The Technical SEO Audit that Saved a Cheyenne Business from a Google Penalty",
    description: "Critical technical SEO audit that identified and fixed issues preventing Google ranking recovery.",
    category: "SEO Services",
    industry: "Digital Marketing",
    location: "Cheyenne, Wyoming",
    client: "Cheyenne E-Commerce Solutions",
    challenge: "Website was hit by a Google algorithm update, lost 60% of organic traffic.",
    solution: "Comprehensive technical SEO audit identifying crawl errors and indexation issues.",
    results: [
      "Recovered 85% of lost traffic",
      "Fixed 47 critical technical issues",
      "Improved Core Web Vitals score",
      "Prevented manual penalty",
    ],
    metrics: { trafficRecovery: "85%", issuesFixed: 47, timeframe: "8 weeks", penaltyPrevented: true },
    featured: false,
    image: "/placeholder.svg?height=400&width=600",
    content: `<h2>The Challenge</h2><p>After a Google algorithm update, Cheyenne E-Commerce Solutions lost 60% of traffic...</p>`,
  },
  {
    slug: "custom-ecommerce-laramie",
    title: "Launch Success: Delivering a Custom E-commerce Website for a Laramie Retailer in 45 Days",
    description: "Fast-track e-commerce development that got a retailer online and generating sales quickly.",
    category: "Web Development",
    industry: "E-Commerce",
    location: "Laramie, Wyoming",
    client: "Laramie Outdoor Gear",
    challenge: "Needed a custom e-commerce website built quickly to capture holiday season sales.",
    solution: "Agile development approach with daily standups and rapid prototyping.",
    results: ["Launched in 45 days", "$180K in first-month sales", "98% uptime", "Mobile conversion rate: 4.2%"],
    metrics: { developmentTime: "45 days", firstMonthSales: "$180K", uptime: "98%", conversionRate: "4.2%" },
    featured: false,
    image: "/placeholder.svg?height=400&width=600",
    content: `<h2>The Challenge</h2><p>Laramie Outdoor Gear needed a custom e-commerce website built in 45 days...</p>`,
  },
  {
    slug: "lead-generation-casper-wy",
    title: "Doubling Qualified Leads for a Casper, WY PPC Campaign with Advanced Audience Targeting",
    description: "Advanced PPC strategy that doubled qualified leads while reducing cost per lead.",
    category: "PPC Advertising",
    industry: "Digital Marketing",
    location: "Casper, Wyoming",
    client: "Casper Business Solutions",
    challenge: "PPC campaigns were generating leads but many were low-quality, wasting ad spend.",
    solution: "Implemented advanced audience targeting, keyword refinement, and landing page optimization.",
    results: [
      "Doubled qualified leads",
      "Cost per lead reduced 35%",
      "Lead quality score improved 60%",
      "ROAS increased to 4.2x",
    ],
    metrics: { leadIncrease: "100%", costPerLeadReduction: "35%", roas: "4.2x", monthlySavings: "$8,000" },
    featured: false,
    image: "/placeholder.svg?height=400&width=600",
    content: `<h2>The Challenge</h2><p>Casper Business Solutions was running PPC campaigns but getting low-quality leads...</p>`,
  },
]

// Industries for filtering
export const industries = [
  "All",
  "Industrial Supply",
  "Legal Services",
  "Automotive Services",
  "Hospitality & Tourism",
  "Digital Marketing",
  "E-Commerce",
  "Web Development",
  "Professional Services",
  "B2B Marketing",
  "Local Services",
]
